#!/bin/bash

# Activate the virtual environment
#cd $(pwd)
DIR=/home/ubuntu/core/user_service/user
cd ${DIR}
source ../env/bin/activate
pip install -r requirements.txt

export FLASK_ENV=development

exec ../env/bin/gunicorn run:app -b 0.0.0.0:8088 \
  --reload \
  --workers 2 \
  --log-level=debug \
  --log-file=-
